name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3. Build & Push Backend
      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-backend:latest ./todo-backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todo-backend:latest

      # 4. Build & Push Frontend
      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-frontend:latest ./todo-frontend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todo-frontend:latest

      # 5. Deploy on EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/todoapp
            docker-compose pull
            docker-compose up -d
          
